[versions]
compileSdk = "36"
targetSdk = "36"
minSdk = "24"
core = "1.7.0"
javax-inject = "1"
core-ktx = "1.17.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
lifecycle-runtime-ktx = "2.9.3"
activity-compose = "1.11.0"
compose-bom = "2025.09.00"
hilt-version = "2.57.1"
androidx_hilt_navigation_compose = "1.3.0"
navigation = "2.9.4"
coroutines-test = "1.10.2"
turbine = "1.2.1"
apollo = "4.3.3"
apollo-mock-server-version = "0.2.0"
viewmodel-compose = "2.9.3"
mockito = "6.0.0"
mockk = "1.14.5"
nhaarman = "2.2.0"
truth = "1.4.4"
okhttp3-loging = "5.1.0"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.4.1"
appcompat = "1.7.1"
timber = "5.0.1"
material = "1.9.1"
google-material = "1.13.0"
compose-lifecycle = "2.9.3"
runner = "1.7.0"
kotlin = "2.1.0"
kotlinxSerializationJson = "1.9.0"
agp = "8.11.1"
baselineprofile = "1.2.4"
profileinstaller = "1.4.1"

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation"}
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx_hilt_navigation_compose" }
hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt-version" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
apollo = { group = "com.apollographql.apollo", name = "apollo-runtime", version.ref = "apollo" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodel-compose" }
hilt-kapt = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-version" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito"}
mockito-nhaarman = { group = "com.nhaarman.mockitokotlin2", name = "mockito-kotlin", version.ref = "nhaarman"}
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk"}
truth = { group = "com.google.truth", name = "truth", version.ref = "truth"}
apollo-test = { group = "com.apollographql.apollo", name = "apollo-testing-support", version.ref = "apollo"}
apollo-mock-server = { group = "com.apollographql.mockserver", name = "apollo-mockserver", version.ref = "apollo-mock-server-version"}
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3-loging"}
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
com-android-test = { id = "com.android.test", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
kotlin-parcelize = { id = "kotlin-parcelize" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }

[bundles]